"""Added user_id in Client model

Revision ID: 63e47f980df8
Revises: 159dce575a86
Create Date: 2026-01-12 21:25:12.355759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63e47f980df8'
down_revision: Union[str, Sequence[str], None] = '159dce575a86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'clients', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_column('clients', 'user_id')
    # ### end Alembic commands ###
