"""added website and notes field in client schema

Revision ID: 7da694ee48fb
Revises: 8aba75ba9784
Create Date: 2026-01-14 20:52:23.709992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7da694ee48fb'
down_revision: Union[str, Sequence[str], None] = '8aba75ba9784'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('website', sa.String(length=225), nullable=True))
    op.add_column('clients', sa.Column('notes', sa.String(length=225), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'notes')
    op.drop_column('clients', 'website')
    # ### end Alembic commands ###
