"""Added total_amount field in invoice schema

Revision ID: 8aba75ba9784
Revises: 68a102ef3a89
Create Date: 2026-01-14 08:56:32.779715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aba75ba9784'
down_revision: Union[str, Sequence[str], None] = '68a102ef3a89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'total_amount')
    # ### end Alembic commands ###
