"""added logo url for client

Revision ID: 9c849708c339
Revises: 7da694ee48fb
Create Date: 2026-01-14 20:59:30.942476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c849708c339'
down_revision: Union[str, Sequence[str], None] = '7da694ee48fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('logo_url', sa.String(length=225), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'logo_url')
    # ### end Alembic commands ###
